runtime: custom
env: flex
env_variables:
  BUCKET_NAME: "stimson-gcs-ds-bucket"
  GOOGLE_APPLICATION_CREDENTIALS: "/app/.GOOGLE_APPLICATION_CREDENTIALS.json"
# https://cloud.google.com/appengine/docs/flexible/python/runtime
runtime_config:
  python_version: 3
threadsafe: yes
# https://cloud.google.com/appengine/docs/flexible/custom-runtimes/configuring-your-app-with-app-yaml

# [START handlers]
handlers:
  - url: /.*
    secure: always
    script: auto
# This sample incurs costs to run on the App Engine flexible environment. 
# The settings below are to reduce costs during testing and are not appropriate
# for production use. For more information, see:
# https://cloud.google.com/appengine/docs/flexible/python/configuring-your-app-with-app-yaml
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.7
  target_concurrent_requests: 10
resources:
  cpu: 2
  memory_gb: 8.0
  disk_size_gb: 10
